version: "3.9"

services:
  database:
    image: postgres:15-alpine
    container_name: database
    environment:
      POSTGRES_DB: carna-database
      POSTGRES_USER: carna
      POSTGRES_PASSWORD: "IjSJmKN1fc#DZBL*NHbVoxIh65JvsFFDO@so"
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carna -d carna-database"]
      interval: 5s
      timeout: 3s
      retries: 15
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USERNAME: carna
      DATABASE_PASSWORD: "IjSJmKN1fc#DZBL*NHbVoxIh65JvsFFDO@so"
      DATABASE_NAME: carna-database
      JWT_SECRET: 4125442A472D4B6150645367556B58703273357638792F423F4528482B4D6251
      JWT_REFRESH_SECRET: 576E5A7134743777217A25432A462D4A614E645267556B58703273357538782F
      PORT: 5000
      NODE_ENV: production
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  db_data:
